version: '2.0'

services:
  mongodb:
    image: "mongo"
    ports:
      - "27018:27018"
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
        - './api:/api'
        - './api/node_modules'
    ports:
      - "6200:6200"
    depends_on:
      - mongodb