const CREATED = 201;
const DELETE_CONTENT = 204;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const UNPROCESSABLE_ENTITY = 422;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {CREATED, DELETE_CONTENT,  BAD_REQUEST, UNAUTHORIZED, UNPROCESSABLE_ENTITY, INTERNAL_SERVER_ERROR};
